### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Drizzt-IT** [BSData/Wild-West-Exodus#12]
Just seen that there are no active developers as it seems...
I would like to do it.

**Comment by Drizzt-IT** [comment]
Any news?

**Comment by Drizzt-IT** [comment]
It seems I can't even open a pull request.
I'd like to contribute and have done some major basic refactoring for the current version.
I completed the warrior nation faction.

**Comment by amis92** [comment]
Hello, @Drizzt-IT. Please accept the invitation in the email or on the [webpage][invitation]. Welcome aboard!

You should have been able to do PRs, though (from your own fork).

Don't forget to read through [wiki][], there are some useful guides, especially [Data Author Guide][guide].

Cheers!

[invitation]: https://github.com/BSData/Wild-West-Exodus/invitations
[wiki]: https://github.com/BSData/catalogue-development/wiki
[guide]: https://github.com/BSData/catalogue-development/wiki/Data-Author-Guide
