### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by nwilson1225** [BSData/Wild-West-Exodus#39]
Hi,

I'd like to assist in getting WWX updated to the latest version.  I'll work on PRs for now.

**Comment by Drizzt-IT** [comment]
Hey cool that you join, what do you mean with PRs?

**Comment by nwilson1225** [comment]
pull requests

**Comment by nwilson1225** [comment]
I'm going to work on outlaws to start, along with copying some of the rules into the main file.  I plan to implement most of the stuff in the main file as Shared Selection Entries with links in the faction files (this is how I am most familiar with battlescribe files and how Star Wars Legion is organized)

**Comment by nwilson1225** [comment]
@amis92 are you able to approve this request?  Thanks.

**Comment by Drizzt-IT** [comment]
@nwilson1225 Hey, im sorry you don't get added.
I also had to go to other places. I went to the battle scribe main projects and asked there.

I'm sorry I'm currently not much of a help.

**Comment by amis92** [comment]
@Drizzt-IT I've granted you admin permissions, you can add @nwilson1225 as collaborator here: https://github.com/BSData/Wild-West-Exodus/settings/collaboration

**Comment by Drizzt-IT** [comment]
Done,
sent the collaboration invite.
Thx @amis92
