### ISSUE TITLE
[Anon] Bug report: WWX.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/Wild-West-Exodus#9]
**File:** WWX.gstz

**BattleScribe version:** 1.15.09

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** I noticed that some characters and upgraded legendary characters are missing. Will these be added?

Great work! Thank you for the data and helping me roll my dice

Teras

**Comment by Drizzt-IT** [comment]
I think this can be closed,
I will redo everything here.
